### ISSUE TITLE
Setting Composer's authors property crashes Future's binary

### ISSUE THREAD

**Issue by ovidiuenache** [evozon/future#3]
The Future binary crashes when used in repositories where the `composer.json` file has the `authors` property set.

**Steps to reproduce the issue:**
1. Require the `evozon/future` library in a project
2. Set the `authors` property in the `composer.json` file of the project to a value like:

```
"authors": [
    {
        "name": "Ioan Ovidiu Enache",
        "email": "i.ovidiuenache@gmail.com"
    }
],
```

3. Run `vendor/bin/future bump-php latest` or `vendor/bin/future bump-deps`

The error that occurs after following the above-mentioned steps is:
```
could not read composer.json: json: cannot unmarshal array into Go struct field schema.authors of type map[string]interface {}
```

**Expected behavior:**
Running `vendor/bin/future bump-php latest` or `vendor/bin/future bump-deps` does not fail if the `authors` property tag is set

**Comment by calinpristavu** [comment]
resolved by #4
